#!/bin/bash

if gcc main.c -o main -lglfw3 -lGL -lm -ldl -lXinerama -lXrandr -lXi \
    -lXcursor -lX11 -lXxf86vm -lpthread -lvulkan -Wall -Wextra \
    -Wpedantic -g ; then
    echo "compile_run: compilation success"
    ./main
else
    echo "compile_run: Compilation failure"
fi
